"""
scripts/setup_sheets.py — One-time KVN Google Sheets setup.

Creates "Korea Velvet News — Master Data" spreadsheet, sets up tabs with
correct headers, and applies data validation for the approved and status
columns.

Usage (no CSV imports needed — use migrate_kvn_sheets.py for data):
    PYTHONPATH=. python scripts/setup_sheets.py

Optional flags:
    --sheets-id XXXX   Open existing sheet instead of creating a new one.
    --keywords-csv     (Optional) Path to Keywords CSV export.
    --glossary-csv     (Optional) Path to Glossary CSV export.
    --articles-csv     (Optional) Path to Articles CSV export.
    --share-email      Extra email to grant editor access (default: seouldesk.help@gmail.com).
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import uuid
from pathlib import Path

import requests

from dotenv import load_dotenv

load_dotenv()

try:
    import gspread
    from google.oauth2.service_account import Credentials
    from google.auth.transport.requests import Request as GoogleRequest
except ImportError:
    print("[ERROR] gspread or google-auth not installed.")
    print("        Run: pip install gspread google-auth")
    sys.exit(1)

# ── Schema definitions ────────────────────────────────────────

ARTICLES_HEADERS = [
    # ── Visible-priority columns (left side) ──────────────────────────────────
    "approved",          # YES/NO dropdown; YES triggers build.py pipeline
    "title_ko",
    "status",
    "published_date",
    "source_name",
    "relevance_score",
    "is_product_news",
    "url",
    "recommendation",
    "is_cluster_rep",
    "cluster_id",
    "input_type",
    # ── Body / translation columns ────────────────────────────────────────────
    "body_ko",
    "title_en",
    "body_en",
    "why_it_matters",       # DINZ relevance sentence (≤25 words), auto-generated by translator
    "source_attribution",   # "Source: Outlet name, Day Month Year"
    "category",             # Market Trends / Regulation & Policy / Products & Brands /
                            # Research & Health / Trade & Distribution / Traditional Medicine
    # ── Secondary metadata ────────────────────────────────────────────────────
    "source_type",
    "tags_internal",
    "image_url",
    "photo_drive_url",
    "direct_text",
    "month_key",
    "glossary_validated",
    "classifier_feedback",
    "id",              # UUID; kept last so key columns stay visible without scrolling
]

KEYWORDS_HEADERS = ["keyword", "is_active", "source", "note"]

GLOSSARY_HEADERS = ["term_ko", "term_en", "term_zh", "category", "note", "is_active"]

REPORTS_HEADERS = ["month", "article_count", "pdf_public_url", "status", "sent_at"]

IGNORED_URLS_HEADERS = ["url", "title_ko", "ignored_date", "reason"]

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]

COMMANDER_EMAIL = "seouldesk.help@gmail.com"

SPREADSHEET_NAME = "Korea Velvet News — Master Data"

# ── Data validation values ────────────────────────────────────

APPROVED_VALUES = ["YES", "NO"]

STATUS_VALUES = [
    "submitted",
    "pending_review",
    "approved",
    "translated",
    "published",
    "translation_failed",
    "ignored",
]


# ── Helpers ───────────────────────────────────────────────────

def _active_flag(raw: str) -> str:
    """Convert Airtable 'checked' or 'TRUE' → 'TRUE'; anything else → 'FALSE'."""
    return "TRUE" if raw.strip().lower() in ("checked", "true", "1", "yes") else "FALSE"


def _read_csv(path: str) -> tuple[list[str], list[list[str]]]:
    """Return (headers, rows) from a CSV file. Strips BOM."""
    rows: list[list[str]] = []
    with open(path, encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        headers = next(reader)
        for row in reader:
            rows.append(row)
    return headers, rows


def _ensure_tab(
    spreadsheet: gspread.Spreadsheet,
    tab_name: str,
    headers: list[str],
    rows: int = 1000,
) -> gspread.Worksheet:
    """Return existing tab or create it with the given headers."""
    try:
        ws = spreadsheet.worksheet(tab_name)
        print(f"  Tab '{tab_name}' already exists — skipping creation.")
        return ws
    except gspread.exceptions.WorksheetNotFound:
        ws = spreadsheet.add_worksheet(title=tab_name, rows=rows, cols=len(headers))
        ws.append_row(headers, value_input_option="USER_ENTERED")
        print(f"  Tab '{tab_name}' created with {len(headers)} columns ({rows} rows).")
        return ws


def _col_letter(index_0based: int) -> str:
    """Convert 0-based column index to Sheets column letter (A, B, ... Z, AA, ...)."""
    result = ""
    n = index_0based + 1
    while n > 0:
        n, remainder = divmod(n - 1, 26)
        result = chr(65 + remainder) + result
    return result


def _add_data_validation(
    spreadsheet: gspread.Spreadsheet,
    worksheet: gspread.Worksheet,
    col_index_0based: int,
    values: list[str],
) -> None:
    """Add a dropdown data validation rule to a column (rows 2 onward) via Sheets API.

    Uses spreadsheet.batch_update() with a setDataValidation request so that
    gspread_formatting is not required as a dependency.
    """
    sheet_id = worksheet.id
    col = col_index_0based

    request = {
        "setDataValidation": {
            "range": {
                "sheetId": sheet_id,
                "startRowIndex": 1,     # row 2 (0-based), skips header
                "endRowIndex": 1000,    # cover all data rows
                "startColumnIndex": col,
                "endColumnIndex": col + 1,
            },
            "rule": {
                "condition": {
                    "type": "ONE_OF_LIST",
                    "values": [{"userEnteredValue": v} for v in values],
                },
                "showCustomUi": True,
                "strict": False,        # warn but allow manual overrides
            },
        }
    }

    spreadsheet.batch_update({"requests": [request]})
    col_letter = _col_letter(col)
    print(f"  Data validation set on column {col_letter}: {', '.join(values)}")


def _clear_data_rows(ws: gspread.Worksheet) -> None:
    """Delete all rows except the header row (row 1)."""
    all_values = ws.get_all_values()
    if len(all_values) <= 1:
        return  # nothing to clear
    ws.delete_rows(2, len(all_values))


def _import_keywords(ws: gspread.Worksheet, csv_path: str) -> int:
    """Import Keywords CSV into the keywords tab. Returns row count."""
    headers, rows = _read_csv(csv_path)
    tab_headers = ws.row_values(1)

    batch: list[list[str]] = []
    for row in rows:
        row_dict = dict(zip(headers, row))
        mapped = {
            "id":        str(uuid.uuid4()),
            "keyword":   row_dict.get("keyword", ""),
            "is_active": _active_flag(row_dict.get("is_active", "")),
            "source":    row_dict.get("source", ""),
            "note":      row_dict.get("note", ""),
        }
        batch.append([mapped.get(h, "") for h in tab_headers])

    if batch:
        ws.append_rows(batch, value_input_option="USER_ENTERED")
    return len(batch)


def _import_glossary(ws: gspread.Worksheet, csv_path: str) -> int:
    """Import Glossary CSV into the glossary tab. Returns row count."""
    headers, rows = _read_csv(csv_path)
    tab_headers = ws.row_values(1)

    batch: list[list[str]] = []
    for row in rows:
        row_dict = dict(zip(headers, row))
        mapped = {
            "id":        str(uuid.uuid4()),
            "term_ko":   row_dict.get("term_ko", ""),
            "term_en":   row_dict.get("term_en", ""),
            "term_zh":   row_dict.get("term_zh", ""),
            "category":  row_dict.get("category", ""),
            "note":      row_dict.get("note", ""),
            "is_active": _active_flag(row_dict.get("is_active", "")),
        }
        batch.append([mapped.get(h, "") for h in tab_headers])

    if batch:
        ws.append_rows(batch, value_input_option="USER_ENTERED")
    return len(batch)


def _import_articles(ws: gspread.Worksheet, csv_path: str) -> int:
    """Import Articles CSV (published/translated only) into the articles tab."""
    headers, rows = _read_csv(csv_path)
    tab_headers = ws.row_values(1)

    batch: list[list[str]] = []
    for row in rows:
        row_dict = dict(zip(headers, row))
        status = row_dict.get("status", "")
        if status not in ("published", "translated"):
            continue

        pd_val = row_dict.get("published_date", "")
        month_key = pd_val[:7] if len(pd_val) >= 7 else ""

        # Map old TRUE/FALSE approved → YES/NO
        raw_approved = row_dict.get("approved", "").strip().upper()
        approved = "YES" if raw_approved in ("TRUE", "YES", "1") else "NO"

        mapped = {
            "id":             str(uuid.uuid4()),
            "url":            row_dict.get("url", ""),
            "title_ko":       row_dict.get("title_ko", ""),
            "title_en":       row_dict.get("title_en", ""),
            "body_ko":        row_dict.get("body_ko", ""),
            "body_en":        row_dict.get("body_en", ""),
            "source_name":    row_dict.get("source_name", ""),
            "source_type":    row_dict.get("source_type", "auto"),
            "published_date": pd_val,
            "status":         status,
            "approved":       approved,
            "month_key":      month_key,
        }
        batch.append([mapped.get(h, "") for h in tab_headers])

    if batch:
        ws.append_rows(batch, value_input_option="USER_ENTERED")
    return len(batch)


# ── Main ──────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="KVN Google Sheets one-time setup.")
    parser.add_argument("--keywords-csv",  default=None, help="(Optional) Path to Keywords CSV export")
    parser.add_argument("--glossary-csv",  default=None, help="(Optional) Path to Glossary CSV export")
    parser.add_argument("--articles-csv",  default=None, help="(Optional) Path to Articles CSV export")
    parser.add_argument("--sheets-id",     default=None, help="Existing Sheets ID (skip creation)")
    parser.add_argument("--share-email",   default=COMMANDER_EMAIL, help="Email to grant editor access")
    args = parser.parse_args()

    # ── Auth ──
    sa_json_raw = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "")
    if not sa_json_raw:
        print("[ERROR] GOOGLE_SERVICE_ACCOUNT_JSON environment variable is not set.")
        sys.exit(1)

    creds = Credentials.from_service_account_info(json.loads(sa_json_raw), scopes=SCOPES)
    client = gspread.authorize(creds)
    print("Authenticated with Google.")

    # ── Open or create spreadsheet ──
    if args.sheets_id:
        spreadsheet = client.open_by_key(args.sheets_id)
        print(f"Opened existing spreadsheet: {spreadsheet.title}")
    else:
        # Use Sheets API v4 spreadsheets.create directly — does NOT require Drive API.
        # gspread's client.create() calls Drive API which may not be enabled.
        creds.refresh(GoogleRequest())
        create_resp = requests.post(
            "https://sheets.googleapis.com/v4/spreadsheets",
            headers={"Authorization": f"Bearer {creds.token}"},
            json={"properties": {"title": SPREADSHEET_NAME}},
            timeout=30,
        )
        create_resp.raise_for_status()
        new_id = create_resp.json()["spreadsheetId"]
        spreadsheet = client.open_by_key(new_id)
        print(f"Created '{SPREADSHEET_NAME}' spreadsheet via Sheets API.")
        print(f"  NOTE: sharing with {args.share_email} requires Drive API.")
        print(f"  Open the URL below and share manually if needed.")
        print(f"  (Or enable Drive API on project velvet-trade-watch to auto-share.)")

    print(f"\nSheets ID: {spreadsheet.id}")
    print(f"URL: https://docs.google.com/spreadsheets/d/{spreadsheet.id}/edit\n")

    # ── Create tabs ──
    print("Setting up tabs...")

    # Delete the default 'Sheet1' if it exists and is empty
    try:
        sheet1 = spreadsheet.worksheet("Sheet1")
        if len(spreadsheet.worksheets()) > 1:
            spreadsheet.del_worksheet(sheet1)
            print("  Removed default 'Sheet1'.")
    except gspread.exceptions.WorksheetNotFound:
        pass

    # articles tab (ARTICLES_HEADERS already includes 'id' as the last entry)
    articles_ws = _ensure_tab(spreadsheet, "articles", ARTICLES_HEADERS)
    keywords_ws = _ensure_tab(spreadsheet, "keywords", ["id"] + KEYWORDS_HEADERS)
    glossary_ws = _ensure_tab(spreadsheet, "glossary", ["id"] + GLOSSARY_HEADERS)
    _ensure_tab(spreadsheet, "reports",   ["id"] + REPORTS_HEADERS)

    # ignored_urls tab — 50 rows only (avoids the 900-empty-row issue)
    _ensure_tab(spreadsheet, "ignored_urls", IGNORED_URLS_HEADERS, rows=50)

    # ── Data validation ──
    print("\nApplying data validation...")

    # approved column: index 0 in ARTICLES_HEADERS
    approved_col = ARTICLES_HEADERS.index("approved")
    _add_data_validation(spreadsheet, articles_ws, approved_col, APPROVED_VALUES)

    # status column: index 2 in ARTICLES_HEADERS
    status_col = ARTICLES_HEADERS.index("status")
    _add_data_validation(spreadsheet, articles_ws, status_col, STATUS_VALUES)

    # ── Optional imports ──
    if args.keywords_csv:
        print(f"\nImporting Keywords from: {args.keywords_csv}")
        kw_count = _import_keywords(keywords_ws, args.keywords_csv)
        print(f"  {kw_count} keywords imported.")

    if args.glossary_csv:
        print(f"\nImporting Glossary from: {args.glossary_csv}")
        gl_count = _import_glossary(glossary_ws, args.glossary_csv)
        print(f"  {gl_count} glossary terms imported.")

    if args.articles_csv:
        print(f"\nImporting Articles from: {args.articles_csv}")
        ar_count = _import_articles(articles_ws, args.articles_csv)
        print(f"  {ar_count} published articles imported.")

    # ── Final instructions ──
    print("\n" + "=" * 60)
    print("SETUP COMPLETE")
    print("=" * 60)
    print(f"\nSheets ID (register as GitHub Secret KVN_SHEETS_ID):")
    print(f"  {spreadsheet.id}")
    print(f"\nURL:")
    print(f"  https://docs.google.com/spreadsheets/d/{spreadsheet.id}/edit")
    print(f"\nNext steps:")
    print("  1. Run: PYTHONPATH=. python scripts/migrate_kvn_sheets.py")
    print("  2. Update KVN_SHEETS_ID in .env and GitHub Secrets")
    print("  3. Open the new sheet → Extensions → Apps Script → paste kvn_apps_script.gs")
    print("  4. Run createKVNForm(), then installTriggers()")


if __name__ == "__main__":
    main()
